-- Multivariate Forecast Table
-- Stores scenario-based forecasts generated by Claude Opus

CREATE TABLE IF NOT EXISTS gpl_multivariate_forecasts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    data_period VARCHAR(50),
    methodology_summary TEXT,
    conservative_json JSONB NOT NULL,
    aggressive_json JSONB NOT NULL,
    demand_drivers_json JSONB,
    executive_summary TEXT,
    model_used VARCHAR(100),
    processing_time_ms INTEGER,
    input_tokens INTEGER,
    output_tokens INTEGER,
    is_fallback BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for quick retrieval of latest forecast
CREATE INDEX IF NOT EXISTS idx_multivariate_forecasts_generated
ON gpl_multivariate_forecasts(generated_at DESC);

-- Comment
COMMENT ON TABLE gpl_multivariate_forecasts IS 'Scenario-based demand forecasts with Conservative and Aggressive projections';
